### ISSUE TITLE
Debian 10 UnboundLocalError: local variable 'skip1st' referenced before assignment

### ISSUE THREAD

**Issue by guerby** [Ho-Ro/Hantek6022API#17]
I installed hantek6022api_2.10.3-1_all.deb on a debian 10 system but when launching capture_6022.py it got a backtrace "UnboundLocalError: local variable 'skip1st' referenced before assignment" :

```
$ capture_6022.py -r 200 -t 0.1 
Capturing 0.1 seconds ...    Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/lib/python3/dist-packages/usb1/__init__.py", line 408, in __callbackWrapper
    callback(self)
  File "/usr/lib/python3/dist-packages/PyHT6022/LibUsbScope.py", line 688, in transfer_callback
    callback(data[::2], data[1::2])
  File "/usr/bin/capture_6022.py", line 152, in pcb
    if skip1st: # skip the 1st (unstable) block
UnboundLocalError: local variable 'skip1st' referenced before assignment
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/lib/python3/dist-packages/usb1/__init__.py", line 408, in __callbackWrapper
    callback(self)
  File "/usr/lib/python3/dist-packages/PyHT6022/LibUsbScope.py", line 688, in transfer_callback
    callback(data[::2], data[1::2])
  File "/usr/bin/capture_6022.py", line 152, in pcb
    if skip1st: # skip the 1st (unstable) block
UnboundLocalError: local variable 'skip1st' referenced before assignment
...
```

Fixed by adding a global statement:

```
# diff -u /usr/bin/capture_6022.py~ /usr/bin/capture_6022.py
--- /usr/bin/capture_6022.py~	2022-03-21 18:51:47.000000000 +0100
+++ /usr/bin/capture_6022.py	2022-07-28 20:56:26.723450178 +0200
@@ -135,6 +135,7 @@
 # scale the data packets and write them into the outfile
 #
 def pcb( ch1_data, ch2_data ):
+    global skip1st,totalsize,dc1,dc2,rms1,rms2,timestep,start_time
     # define "static" variables
     if 'av1' not in pcb.__dict__:
         pcb.av1 = 0
```

**Comment by guerby** [comment]
Note: same issue on debian 11, same fix is working
