### ISSUE TITLE
Windows installation problem

### ISSUE THREAD

**Issue by fhsakaci** [Ho-Ro/Hantek6022API#20]
setup.py is not working in windows. I take in the following error. 

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\Hantek6022API\setup.py", line 20, in <module>
          setup(
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 558, in run
          self.run_command(cmd_name)
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\distutils\command\install_data.py", line 56, in run
          dir = convert_path(f[0])
        File "c:\users\administrator\appdata\local\programs\python\python39\lib\distutils\util.py", line 125, in convert_path
          raise ValueError("path '%s' cannot end with '/'" % pathname)
      ValueError: path 'share/doc/hantek6022api/' cannot end with '/'
      [end of output]

I changed setup.py in the following and it is working now. I just removed "/" in "share/doc/hantek6022api/". I think you should change this line for windows. 

data_files=[
    ( 'share/doc/hantek6022api', [ 'README.md', 'CHANGELOG', 'LICENSE' ] ),
]

**Comment by Ho-Ro** [comment]
Should be fixed with latest commit.
```python
data_files=[
    ( os.path.join( 'share', 'doc', 'hantek6022api' ), [ 'README.md', 'CHANGELOG', 'LICENSE' ] ),
]
```
@fhsakaci Please check.

**Comment by Ho-Ro** [comment]
So far no answer, it seems to be solved. Closing now.
